version: 2.1

commands:
  init-git-lfs:
    description: "Initializes Git-LFS from cache"
    steps:
      - run:
          name: Collect Git-LFS asset hashes
          command: git lfs ls-files -l | cut -d' ' -f1 | sort > ~/.gitlfs-assets

      - restore_cache:
          name: Restore Git-LFS
          key: v1-git-lfs-{{ checksum "~/.gitlfs-assets" }}

      - run:
          name: Git-LFS pull
          command: git lfs pull

      - save_cache:
          name: "Cache Git-LFS"
          key: v1-git-lfs-{{ checksum "~/.gitlfs-assets" }}
          paths:
            - .git/lfs

jobs:
  build-java:
    resource_class: small
    docker:
      - image: cimg/openjdk:11.0.20
    working_directory: ~/repo
    parameters:
      projectdir:
        type: string
    steps:
      - checkout
      - init-git-lfs
      - attach_workspace:
          at: /home/circleci/repo
      - run:
          name: Build project
          command: |
              cd << parameters.projectdir >>
              ./build.sh
      - run:
          name: Test project
          command: |
              cd << parameters.projectdir >>
              ./test.sh
      - persist_to_workspace:
          root: /home/circleci/repo
          paths:
            - << parameters.projectdir >>

workflows:
  build:
    jobs:
      - build-java:
          name: build-library1
          projectdir: java/libraries/library1
          requires:
            - build-library2
            - build-library3
      - build-java:
          name: build-library2
          projectdir: java/libraries/library2
          requires: []
      - build-java:
          name: build-library3
          projectdir: java/libraries/library3
          requires: []
      - build-java:
          name: build-service1
          projectdir: java/services/service1
          requires:
            - build-library1